version: 2.8.{build}

environment:
  BUILD_REPO_URL:
    secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCyOLKGt19Qrk45/TrTFlGMQ==

install:
  - ps: Install-Product node 8
  - npm install

build_script:
  - node_modules\.bin\npm build

test_script:
  - node_modules\.bin\npm test

after_test:
  - node_modules\.bin\zip -r dist\angular2-sample.zip dist\angular2-sample
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName ReleaseArtifacts }
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" node_modules\.bin\grunt publish

artifacts:
  - path: .\*.zip
    name: ReleaseArtifacts

deploy:
  provider: GitHub
  auth_token:
    secure: ab5b61b19ac1b7abc61c138358790ebed6cf9932
  artifact: ReleaseArtifacts
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: GniMpFE62HprSyQNQoej/VSBnxn2GNnTrca3BnF8+ikMdqduO4Ts4t297teZF6wDAmGwnOtXusctUla8+WxLFkIztvVCS2Z1RG/DvEDYoc0=
